version: '3.8'

services:
  frontend:
    build: .
    command: node_modules/.bin/next start
    env_file:
      - .env
  nginx:
    depends_on:
      - frontend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    image: nginx:stable-alpine
    entrypoint: nginx -g 'daemon off;'
    ports:
      - 3000:80
