export { default as BxBell } from './assets/bx-bell.svg'
export { default as BxUserCircle } from './assets/bx-user-circle.svg'
export { default as BxHeart } from './assets/bx-heart.svg'
export { default as BxMenu } from './assets/bx-menu.svg'
export { default as BxShoppingBag } from './assets/bx-shopping-bag.svg'
export { default as BxSearch } from './assets/bx-search.svg'
