//BX
export { default as BxBell } from './assets/bx-bell.svg'
export { default as BxUserCircle } from './assets/bx-user-circle.svg'
export { default as BxHeart } from './assets/bx-heart.svg'
export { default as BxMenu } from './assets/bx-menu.svg'
export { default as BxShoppingBag } from './assets/bx-shopping-bag.svg'
export { default as BxSearch } from './assets/bx-search.svg'
export { default as BxHomeAlt } from './assets/bx-home-alt.svg'
export { default as BxArrowBack } from './assets/bx-arrow-back.svg'
export { default as BxChevronLeft } from './assets/bx-chevron-left.svg'
export { default as BxChevronRight } from './assets/bx-chevron-right.svg'
export { default as BxPackage } from './assets/bx-package.svg'
export { default as BxRightArrow } from './assets/bx-right-arrow-alt.svg'
export { default as BxMinus } from './assets/bx-minus.svg'
export { default as BxPlus } from './assets/bx-plus.svg'
export { default as BxsSquare } from './assets/bxs-square.svg'
export { default as BxsTrashAlt } from './assets/bx-trash-alt.svg'

//BXS
export { default as BxsRightArrow } from './assets/bxs-right-arrow.svg'
export { default as BxsDownArrow } from './assets/bxs-down-arrow.svg'
export { default as BxsUpArrow } from './assets/bxs-up-arrow.svg'
export { default as BxsGift } from './assets/bxs-gift.svg'
export { default as BxsTruck } from './assets/bxs-truck.svg'
